---
- name: AWS and System Setup
  block:

    - name: Install telnet package for network connectivity testing
      ansible.builtin.dnf:
        name: telnet
        state: present

- name: Postfix Initial Setup
  block:
    - name: Install postfix, rsync and nc packages for email delivery setup
      ansible.builtin.dnf:
        name:
          - postfix
          - rsync
          - nc
        state: present

    - name: Install pexpect library in the Python environment (dependency for copying files from old server)
      ansible.builtin.pip:
        name: pexpect
        state: present

    - name: Ensure the target directory exists on this server
      ansible.builtin.file:
        path: /etc/postfix
        state: directory
        owner: root
        group: root
        mode: "0755"



- name: Postfix Service Configuration
  block:
    - name: Change ownership of /etc/postfix directory to root
      ansible.builtin.file:
        path: /etc/postfix
        owner: root
        group: root
        recurse: yes

    - name: Set permissions of /etc/postfix directory to 744
      ansible.builtin.file:
        path: /etc/postfix
        mode: "0744"

    - name: Ensure postfix service is enabled and running
      ansible.builtin.service:
        name: postfix
        state: started
        enabled: yes
      notify: restart postfix

    - name: Generate postmap for access file
      command: postmap /etc/postfix/access
      args:
        creates: /etc/postfix/access.db

    - name: Generate postmap for blacklisted_domains file
      command: postmap /etc/postfix/blacklisted_domains
      args:
        creates: /etc/postfix/blacklisted_domains.db

    - name: Generate postmap for blacklisted_senders file
      command: postmap /etc/postfix/blacklisted_senders
      args:
        creates: /etc/postfix/blacklisted_senders.db

    - name: Generate postmap for sasl_passwd file
      command: postmap /etc/postfix/sasl_passwd
      args:
        creates: /etc/postfix/sasl_passwd.db

- name: Mail Testing
  block:
    - name: Get domain from AWS SES in us-east-2
      command: aws ses list-identities --region us-east-2
      register: ses_output_us_east_2
      ignore_errors: true

    - name: Get domain from AWS SES in us-east-1 if not found in us-east-2
      command: aws ses list-identities --region us-east-1
      register: ses_output_us_east_1
      when: >
        ses_output_us_east_2.rc != 0 or 
        (ses_output_us_east_2.rc == 0 and ((ses_output_us_east_2.stdout | from_json).Identities | length == 0))
      ignore_errors: true

    - name: Combine identity lists from both regions
      set_fact:
        # Get identities from us-east-2 if command succeeded
        identities_2: "{{ (ses_output_us_east_2.stdout | from_json).Identities | default([]) if (ses_output_us_east_2 is defined and ses_output_us_east_2.rc == 0) else [] }}"
        # Get identities from us-east-1 if command ran and succeeded
        identities_1: "{{ (ses_output_us_east_1.stdout | from_json).Identities | default([]) if (ses_output_us_east_1 is defined and ses_output_us_east_1.rc is defined and ses_output_us_east_1.rc == 0) else [] }}"

    - name: Set final domain variable from combined list
      set_fact:
        all_identities: "{{ identities_2 + identities_1 }}"
        # Filter to get only domain names (not email addresses)
        domain_candidates: "{{ (identities_2 + identities_1) | select('match', '^[^@]+\\.[a-z]+$') | list }}"

    - name: Select best domain
      set_fact:
        domain: "{{ domain_candidates | first | default((identities_2 + identities_1) | first | default('')) }}"

    - name: Debug all variables
      debug:
        msg: |
          US-East-2 identities: {{ identities_2 }}
          US-East-1 identities: {{ identities_1 }}
          All identities: {{ all_identities }}
          Domain candidates: {{ domain_candidates }}
          Selected domain: {{ domain }}

    - name: Send test email using netcat
      shell: |
        echo -e "HELO {{ domain }}\nMAIL FROM: <donotreply@{{ domain }}>\nRCPT TO: <{{ recipient }}>\nDATA\nSubject: test\n\nThis is a test email from Postfix.\n.\nQUIT" | nc localhost 25
      register: email_test_output

    - name: Verify email was queued successfully
      fail:
        msg: "Postfix email test failed! Output: {{ email_test_output.stdout }}"
      when: not email_test_output.stdout is search(pattern)
