# ansible/fl_apps/txerp/gw-b/tasks/main.yml
---
- name: Debug client_name variable
  ansible.builtin.debug:
    # Reference the variable from the dictionary we created in pre_tasks
    var: final_vars.client_name

- name: Set hostname using hostnamectl
  ansible.builtin.command:
    cmd: hostnamectl set-hostname "{{ final_vars.client_name }}-gw-b-v2"
  become: true

- name: Include Crowdstrike role
  ansible.builtin.include_role:
    name: "{{ playbook_dir }}/../common/crowdstrike"

- name: Include Automox role
  ansible.builtin.include_role:
    name: "{{ playbook_dir }}/../common/automox"

- name: Include boto3 role
  ansible.builtin.include_role:
    name: "{{ playbook_dir }}/../common/boto3"

- name: Include ecs_scaling_crons role
  ansible.builtin.include_role:
    name: "{{ playbook_dir }}/../common/ecs_scaling_crons"

- name: Include observium_gw_config tasks
  ansible.builtin.include_tasks: observium_gw_config.yml

- name: Include observium role
  ansible.builtin.include_role:
    name: "{{ playbook_dir }}/../common/observium"

- name: Include postfix_gw_config tasks
  ansible.builtin.include_tasks: postfix_gw_config.yml
  vars:
    client_name: "{{ final_vars.client_name }}"

- name: Include postfix smtp role
  ansible.builtin.include_role:
    name: "{{ playbook_dir }}/../common/smtp"
  vars:
    client_name: "{{ final_vars.client_name }}"
