---
- name: Configure all services for gw-b
  block:

    - name: Debug client_name variable
      debug:
        var: client_name


    - name: Include observium role
      ansible.builtin.include_role:
        name: ../../../../common/observium

    - name: Include smtp role
      ansible.builtin.include_role:
        name: ../../../../common/smtp
