---
- name: Install AWS boto3 Python SDK for AWS interactions
  ansible.builtin.pip:
    name: boto3
    state: present
    version: "{{ boto3_version }}"

- name: Install AWS boto3 Python SDK (pinned)
  ansible.builtin.pip:
    name: boto3
    state: present
    version: "{{ boto3_version }}"

- name: Clear Ansible's Python module cache
  ansible.builtin.meta: clear_facts

- name: Validate boto3 installation and availability
  ansible.builtin.command:
    cmd: python3 -c "import boto3, botocore; print('AWS libraries available')"
  register: aws_lib_check
  retries: 3
  delay: 2
  until: aws_lib_check.rc == 0
  changed_when: false

- name: Verify installed boto3 version matches required version {{ boto3_version }}
  ansible.builtin.command:
    cmd: python3 -c "import boto3; print(boto3.__version__)"
  register: boto3_check
  changed_when: false

- name: Display current boto3 version for verification
  ansible.builtin.debug:
    msg: "{{ boto3_check.stdout }}"
