---
- name: Configure all services for gw-b
  hosts: all
  become: true
  vars:
    ansible_python_interpreter: auto
    # Can override any variables from the common role here if needed
    client_name: "whcopa" # Can be overridden for specific client (used for fethching old gateway b server using tag name)

  tasks:
    - name: Include observium role
      ansible.builtin.include_role:
        name: ../../../../common/observium

    - name: Include smtp role
      ansible.builtin.include_role:
        name: ../../../../common/smtp
