---
- name: Configure all services for gw-a
  hosts: all
  become: true
  # vars:
    # ansible_python_interpreter: /usr/bin/python3
    # Override variables if needed
    # client_name: "arlitx" # Can be overridden for specific client (Used for fetching stunnel certificate and configuration)

  tasks:

    - name: Include stunnel role
      ansible.builtin.include_role:
        name: ../../../../common/stunnel
