# ansible/fl_apps/txerp/gw-b/tasks/main.yml
---
- name: Debug client_name variable
  ansible.builtin.debug:
    # Reference the variable from the dictionary we created in pre_tasks
    var: final_vars.client_name

- name: Set hostname using hostnamectl
  ansible.builtin.command:
    cmd: hostnamectl set-hostname "{{ final_vars.client_name }}-gw-a-v2"
  become: true

- name: Collect AWS EC2 instance metadata for configuration
  amazon.aws.ec2_metadata_facts:

- name: Display current AWS region from instance metadata
  debug:
    msg: "The AWS region is {{ ansible_ec2_instance_identity_document_region }}"

- name: Include stunnel role
  ansible.builtin.include_role:
    name: "{{ playbook_dir }}/../common/stunnel"
  vars:
    client_name: "{{ final_vars.client_name }}"
