# ansible/fl_apps/txerp/gw-b/tasks/main.yml
---
- name: Debug client_name variable
  ansible.builtin.debug:
    # Reference the variable from the dictionary we created in pre_tasks
    var: final_vars.client_name

- name: Include stunnel role
  ansible.builtin.include_role:
    name: "{{ playbook_dir }}/../common/stunnel"
  vars:
    client_name: "{{ final_vars.client_name }}"

