---
- name: Get PLATFORM_ID from /etc/os-release
  ansible.builtin.shell: "grep ^PLATFORM_ID= /etc/os-release | cut -d= -f2 | tr -d '\"'"
  register: platform_id
  changed_when: false

- name: Install Crowdstrike if os is amazonlinux
  when: platform_id.stdout == "platform:al2023"
  block:
    - name: Download Crowdstrike RPM from S3
      aws_s3:
        bucket: ferp-build
        object: crowdstrike-packages/falcon-sensor-6.57.0-15402.amzn2023.x86_64.rpm
        dest: /tmp/falcon-sensor-6.57.0-15402.amzn2023.x86_64.rpm
        mode: get
      register: s3_download

    - name: Install Crowdstrike RPM
      dnf:
        name: /tmp/falcon-sensor-6.57.0-15402.amzn2023.x86_64.rpm
        state: present
        disable_gpg_check: yes

    - name: Get Crowdstrike CID from SSM Parameter Store using AWS CLI
      ansible.builtin.shell: |
        aws ssm get-parameter \
          --name "crowd-strike-cid" \
          --with-decryption \
          --region "us-east-2" \
          --query 'Parameter.Value' \
          --output text
      register: crowdstrike_cid_result
      retries: 5
      delay: 5
      until: crowdstrike_cid_result.rc == 0

    - name: Set Crowdstrike CID fact
      ansible.builtin.set_fact:
        crowdstrike_cid: "{{ crowdstrike_cid_result.stdout }}"

    - name: Set Crowdstrike CID
      command: /opt/CrowdStrike/falconctl -s -f --cid={{ crowdstrike_cid }}
      notify: restart crowdstrike

    - name: Set Crowdstrike tags
      command: /opt/CrowdStrike/falconctl -s -f --tags='FrontlineProduct-erp_teams,Owner-DIST_Technology_SaaSIO_SRE_Team_Cask,Environment-aws_prod'
      notify: restart crowdstrike
